# https://github.com/lowlighter/metrics

name: GitHub Metrics
on:
  schedule:
    - cron: "0 3 1 * *"
  push:
    branches: 
      - main
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
      - name: Personal metrics
        uses: lowlighter/metrics@master
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: fujiawei-dev
          config_timezone: Asia/Shanghai
          config_order: base.header, isocalendar, languages, base.repositories, followup
          config_padding: 10%
          use_prebuilt_image: master
          base: "header, repositories"
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_threshold: 5%
          plugin_languages_limit: 6
          plugin_lines: yes
          plugin_traffic: yes
          plugin_followup: yes
